const COLORS = {
  CINZA_CLARO: "#F2F2F2",
  CINZA_MEDIO: "#CCCCCC",
  CINZA_ESCURO: "#4D4D4D",
  LARANJA: "#E08314",
  VERDE_SUCESSO: "#4CAF50",
  VERMELHO_FALHA: "#F44336",
};

export default COLORS;
